name: "release"
on:
  release:
    types: [published]
jobs:
  build:
    name: "release"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@master
      - name: "publish"
        uses: actions/npm@master
        with:
          args: publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
